### ISSUE TITLE
Question: is there a way to set environment variables?

### ISSUE THREAD

**Issue by maraujop** [craigatk/maestro-gradle-plugin#18]
Hi Craig,

I'm trying your gradle plugin for maestro and got it working. In my test files I'm using an environment variable in some flows

`maestro test -e whatever=19 flowfile.yml`

Is there a way to set this in your plugin? 

Also another question, right now maestro doesn't support execution order, but I have the feeling it would be feasible to support it in this plugin, would it be an option?

Thanks, cheers
Miguel

**Comment by craigatk** [comment]
Hi Miguel,

Good question about the environment variable support, I'll work on adding support for that into the plugin.

On the execution order, currently the plugin just lists all the files in the directory and runs them in whichever arbitrary order the directory access code returns. Out of curiosity, what are you looking to accomplish with a specific execution order?

**Comment by craigatk** [comment]
I added support for passing parameters to the Maestro command via `-e` in the new 1.2.0 version of the plugin - docs here on how to pass them https://github.com/craigatk/maestro-gradle-plugin#flow-parameters
